<Project><PropertyGroup><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>12</LangVersion><EnableWindowsTargeting>true</EnableWindowsTargeting><Version>0.2.0</Version><Company>6ixMedia SA</Company><Authors>6ixMedia SA</Authors><Deterministic>true</Deterministic></PropertyGroup></Project>
