using Microsoft.Data.Sqlite;
namespace Again.Core;
public sealed class Store {
 readonly string _connection;
 public Store(string path){Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);_connection=new SqliteConnectionStringBuilder{DataSource=path,Pooling=false}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS migrations(version INTEGER PRIMARY KEY); CREATE TABLE IF NOT EXISTS records(kind TEXT NOT NULL,id TEXT NOT NULL,version INTEGER NOT NULL,json TEXT NOT NULL,updated TEXT NOT NULL,PRIMARY KEY(kind,id,version)); INSERT OR IGNORE INTO migrations VALUES(1);";cmd.ExecuteNonQuery();}
 SqliteConnection Open(){var c=new SqliteConnection(_connection);c.Open();return c;}
 public void Save<T>(string kind,string id,int version,T value){using var c=Open();using var tx=c.BeginTransaction();using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO records VALUES($kind,$id,$version,$json,$updated) ON CONFLICT(kind,id,version) DO UPDATE SET json=excluded.json,updated=excluded.updated";cmd.Parameters.AddWithValue("$kind",kind);cmd.Parameters.AddWithValue("$id",id);cmd.Parameters.AddWithValue("$version",version);cmd.Parameters.AddWithValue("$json",WorkflowJson.Write(value));cmd.Parameters.AddWithValue("$updated",DateTimeOffset.UtcNow.ToString("O"));cmd.ExecuteNonQuery();tx.Commit();}
 public List<T> List<T>(string kind,bool allVersions=false){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText=allVersions?"SELECT json FROM records WHERE kind=$kind ORDER BY updated DESC":"SELECT r.json FROM records r WHERE kind=$kind AND version=(SELECT MAX(s.version) FROM records s WHERE s.kind=r.kind AND s.id=r.id) ORDER BY updated DESC";cmd.Parameters.AddWithValue("$kind",kind);using var reader=cmd.ExecuteReader();var result=new List<T>();while(reader.Read())result.Add(WorkflowJson.Read<T>(reader.GetString(0)));return result;}
 public void Delete(string kind,string? id=null){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM records WHERE kind=$kind"+(id is null?"":" AND id=$id");cmd.Parameters.AddWithValue("$kind",kind);if(id is not null)cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
 public void SaveDraft(Draft d)=>Save("draft",d.Id.ToString(),1,d with{Updated=DateTimeOffset.UtcNow});
 public Workflow SaveAndRun(Draft draft){WorkflowJson.Validate(draft.Workflow);var previous=List<Workflow>("workflow").FirstOrDefault(w=>w.Id==draft.Workflow.Id);if(previous is not null&&WorkflowJson.Write(previous)==WorkflowJson.Write(draft.Workflow)){SaveDraft(draft with{State="Ready to run"});return previous;}var saved=draft.Workflow with{Version=(previous?.Version??0)+1,Modified=DateTimeOffset.UtcNow};Save("workflow",saved.Id.ToString(),saved.Version,saved);SaveDraft(draft with{Workflow=saved,State="Ready to run"});return saved;}
 public void SaveSettings(Settings s)=>Save("settings","settings",1,s);
 public Settings Settings()=>List<Settings>("settings").FirstOrDefault()??new Settings();
}
