<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>AGAIN</AssemblyName><ApplicationIcon>../../assets/again.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../Again.Core/Again.Core.csproj"/><ProjectReference Include="../Again.Imaging/Again.Imaging.csproj"/><ProjectReference Include="../Again.Windows/Again.Windows.csproj"/></ItemGroup></Project>
